[package]
name = "jiankong"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.33.1"
time = { version = "0.3", features = ["macros", "formatting"] }
env_logger = "0.11.6"
log = "0.4.26"
lettre = "0.11.17"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"